"""
Django settings for proyecto1 project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from import_export.formats.base_formats import CSV, TSV, JSON, HTML, XLS, XLSX

# 🔧 1. Directorio base
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 2. Seguridad
SECRET_KEY = 'django-insecure-=48*v$!idcmg*^9mq86&xxg&2ky5c2q(u(v@xj5nsi4=4x+3z!'
DEBUG = True
ALLOWED_HOSTS = []

# 📂 3. Archivos estáticos y media
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ✅ Dominio para exportar links en Excel
APP_DOMAIN = "http://localhost:8000"  # ⚠️ Cambia esto en producción

# 🧩 4. Aplicaciones instaladas
INSTALLED_APPS = [
    'jazzmin',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminproyecto1.apps.Adminproyecto1Config',
]

# ⚙️ 5. Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔗 6. URLs
ROOT_URLCONF = 'proyecto1.urls'

# 🖼️ 7. Templates (con soporte para tus HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'adminproyecto1', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🐍 8. WSGI
WSGI_APPLICATION = 'proyecto1.wsgi.application'

# 🗃️ 9. Base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cenaped',
        'USER': 'postgres',
        'PASSWORD': 'ferjadith1708',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# 🔐 10. Validadores de contraseña
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌐 11. Idioma y zona horaria
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# 🆔 12. Clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🎨 13. Jazzmin (configuración del panel admin)
JAZZMIN_SETTINGS = {
    "site_title": "Panel de Control",
    "site_header": "Administración CENAPED",
    "welcome_sign": "Bienvenido al sistema de gestión de formación",
    "login_logo": "img/logo_cenaped.png",
    "site_logo": "img/logo_cenaped.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_brand": "CENAPED",
    "site_icon": "img/logo_cenaped.png",

    # 📂 Archivos personalizados (css/js)
    "custom_css": "css/login.css",
    "custom_js": "js/pepito.js",

    # 📌 Navegación
    "show_sidebar": True,
    "navigation_expanded": True,

    # 🔗 Menú superior
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "admin-dashboard", "icon": "fas fa-chart-line"},
    ],

    # 📌 Menú lateral con íconos
    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
        "adminproyecto1.Adminproyecto1": "fas fa-cogs",
        "adminproyecto1.Areas": "fas fa-th-large",
        "adminproyecto1.BitacoraDocente": "fas fa-book-open",
        "adminproyecto1.Entidad": "fas fa-building",
        "adminproyecto1.Facultad": "fas fa-university",
        "adminproyecto1.FormacionDocente": "fas fa-chalkboard-teacher",
        "adminproyecto1.Formacion": "fas fa-book",
        "adminproyecto1.Modalidad": "fas fa-exchange-alt",
        "adminproyecto1.Programa": "fas fa-project-diagram",
        "adminproyecto1.Rol": "fas fa-user-tag",
        "adminproyecto1.TipoFormacion": "fas fa-list-alt",
        "adminproyecto1.Usuario": "fas fa-users",
    
    },

    "copyright": "CENAPED © 2025",
}

# 🎨 14. Ajustes visuales extra de Jazzmin



# 📦 15. Configuración de django-import-export
IMPORT_EXPORT_USE_TRANSACTIONS = True

IMPORT_EXPORT_FORMATS = [
    CSV,
    TSV,
    JSON,
    HTML,
    XLS,
    XLSX,
]
