# Generated by Django 5.2.4 on 2025-08-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('tipo_de_entidad', models.CharField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entidad',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id_modalidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modalidad',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipos_de_rol', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoFormacion',
            fields=[
                ('id_tipo_formacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('formaciones', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_formacion',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id_formacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('formacion', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_de_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('incertidumbre_horaria', models.CharField(blank=True, max_length=100, null=True)),
                ('id_entidad', models.ForeignKey(blank=True, db_column='id_entidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.entidad')),
                ('id_modalidad', models.ForeignKey(blank=True, db_column='id_modalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.modalidad')),
                ('id_tipo_formacion', models.ForeignKey(blank=True, db_column='id_tipo_formacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.tipoformacion')),
            ],
            options={
                'db_table': 'formacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('tipo_de_documento', models.CharField(blank=True, null=True)),
                ('numero_de_documento', models.BigIntegerField()),
                ('lugar_de_residencia', models.CharField(blank=True, null=True)),
                ('titulo_de_pregrado', models.CharField(blank=True, null=True)),
                ('titulo_de_nivel_maximo', models.CharField(blank=True, null=True)),
                ('tipo_de_vinculo', models.CharField(blank=True, null=True)),
                ('fecha_de_ingreso', models.DateField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='FormacionDocente',
            fields=[
                ('id_formaciondocente', models.BigAutoField(db_column='id_FormacionDocente', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('pdf_certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('id_formacion', models.ForeignKey(blank=True, db_column='id_formacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.formacion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.usuario')),
            ],
            options={
                'db_table': 'formacion_docente',
            },
        ),
        migrations.AddField(
            model_name='formacion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.usuario'),
        ),
    ]
