# Generated by Django 5.2.4 on 2025-08-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.BigAutoField(db_column='id_facultad', primary_key=True, serialize=False)),
                ('facultad', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'facultad',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.BigAutoField(db_column='id_programa', primary_key=True, serialize=False)),
                ('Programa', models.CharField(blank=True, max_length=200, null=True)),
                ('id_facultad', models.ForeignKey(blank=True, db_column='id_facultad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='adminproyecto1.facultad')),
            ],
            options={
                'db_table': 'programa',
            },
        ),
    ]
