# Generated by Django 5.2.4 on 2025-08-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0002_facultad_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_programa',
            field=models.ForeignKey(blank=True, db_column='id_PROGRAMA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.programa'),
        ),
    ]
