# Generated by Django 5.2.4 on 2025-08-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0003_usuario_id_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaciondocente',
            name='id_programa',
            field=models.ForeignKey(blank=True, db_column='id_programa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminproyecto1.programa'),
        ),
    ]
