# Generated by Django 5.2.4 on 2025-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0004_formaciondocente_id_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaciondocente',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
