# Generated by Django 5.2.4 on 2025-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0005_formaciondocente_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaciondocente',
            name='serial',
            field=models.CharField(default='PENDIENTE', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
