# Generated by Django 5.2.4 on 2025-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0006_alter_formaciondocente_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaciondocente',
            name='estado',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('finalizado_aprobado', 'Finalizado - Aprobado'), ('finalizado_no_aprobado', 'Finalizado - No Aprobado')], default='cursando', max_length=30),
        ),
    ]
