# Generated by Django 5.2.4 on 2025-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0007_alter_formaciondocente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaciondocente',
            name='estado',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('finalizado', 'Finalizado')], default='cursando', max_length=30),
        ),
    ]
