# Generated by Django 5.2.4 on 2025-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0008_alter_formaciondocente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
