# Generated by Django 5.2.4 on 2025-08-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0009_formacion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_areas', models.BigAutoField(db_column='id_areas', primary_key=True, serialize=False)),
                ('areas', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='formacion',
            name='id_areas',
            field=models.ForeignKey(blank=True, db_column='id_areas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacion', to='adminproyecto1.areas'),
        ),
    ]
