# Generated by Django 5.2.4 on 2025-08-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0010_areas_formacion_id_areas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areas',
            table='Areas',
        ),
    ]
