# Generated by Django 5.2.4 on 2025-08-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0011_alter_areas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='momento',
            field=models.CharField(choices=[('semestre', 'Semestre'), ('intersemestral', 'Intersemestral')], default='semestre', max_length=20),
        ),
    ]
