# Generated by Django 5.2.4 on 2025-08-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0012_formacion_momento'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaciondocente',
            name='desempeño_laboral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='formaciondocente',
            name='evaluacion_de_conocimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='formaciondocente',
            name='nivel_de_satisfaccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterModelTable(
            name='formaciondocente',
            table=None,
        ),
    ]
