# Generated by Django 5.2.4 on 2025-09-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0014_alter_formaciondocente_desempeño_laboral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='momento',
            field=models.CharField(choices=[('semestre_1', 'Semestre 1'), ('semestre_2', 'Semestre 2'), ('intersemestral_1', 'Intersemestral 1'), ('intersemestral_2', 'Intersemestral 2')], default='semestre', max_length=25),
        ),
    ]
