# Generated by Django 5.2.4 on 2025-09-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0015_usuario_activo_alter_formacion_momento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('año', models.IntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminproyecto1.facultad')),
                ('formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminproyecto1.formacion')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminproyecto1.programa')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminproyecto1.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproyecto1.usuario')),
            ],
        ),
    ]
