# Generated by Django 5.2.4 on 2025-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0016_bitacoradocente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitacoraDocente',
        ),
    ]
