# Generated by Django 5.2.4 on 2025-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0017_delete_bitacoradocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('periodo', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('inter1', 'Intersemestral 1'), ('inter2', 'Intersemestral 2'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Si este periodo está en curso.')),
            ],
            options={
                'db_table': 'periodo_academico',
                'ordering': ['-anio', 'periodo'],
                'unique_together': {('anio', 'periodo')},
            },
        ),
    ]
