# Generated by Django 5.2.4 on 2025-09-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0018_periodoacademico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
    ]
