# Generated by Django 5.2.4 on 2025-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0019_delete_periodoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('total_usuarios', models.IntegerField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consolidado',
            },
        ),
    ]
