# Generated by Django 5.2.4 on 2025-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproyecto1', '0020_consolidado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consolidado',
        ),
    ]
